<a href="https://colab.research.google.com/github/brianchen989/learnAi/blob/main/%E5%A4%9A%E9%87%8D%E7%B7%9A%E6%80%A7%E5%9B%9E%E6%AD%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [189]:
import pandas as pd
url = "https://raw.githubusercontent.com/GrandmaCan/ML/main/Resgression/Salary_Data2.csv"
data = pd.read_csv(url)
data

YearsExperience EducationLevel City  Salary
0               3.0             大學  城市A    45.9
1               7.8           碩士以上  城市C    80.5
2               2.3           高中以下  城市A    25.2
3               5.1           高中以下  城市A    30.4
4              10.0           碩士以上  城市B    65.7
5               1.2           碩士以上  城市C    60.8
6               8.6             大學  城市C    50.1
7               6.9           碩士以上  城市A    70.3
8               4.2             大學  城市A    40.7
9               2.4           高中以下  城市A    28.1
10              5.3           高中以下  城市A    32.0
11              3.9             大學  城市A    48.3
12              7.2           碩士以上  城市C    84.2
13             10.0           碩士以上  城市B    70.9
14              1.5           碩士以上  城市C    62.4
15              8.4             大學  城市C    55.6
16              6.5           碩士以上  城市A    72.7
17              4.8             大學  城市A    42.9
18              2.1           高中以下  城市A    26.5
19              5.2           高中以下  城市A    31.6
20              3.5             大學  城市A    43.8
21              7.6           碩士以上  城市C    78.3
22             10.0           碩士以上  城市B    63.6
23              1.8           碩士以上  城市C    58.0
24              8.2             大學  城市C    48.3
25              6.3           碩士以上  城市A    68.4
26              4.6             大學  城市A    38.5
27              2.5           高中以下  城市A    24.9
28              5.0           高中以下  城市A    29.7
29              3.6             大學  城市A    41.6
30              7.4           碩士以上  城市C    76.9
31             10.0           碩士以上  城市B    60.2
32              1.7           碩士以上  城市C    56.3
33              8.0             大學  城市C    45.2
34              6.1           碩士以上  城市A    65.9
35              4.3             大學  城市A    36.7

In [190]:
#文字量化
data["EducationLevel"] = data["EducationLevel"].map({"高中以下":0,"大學":1,"碩士以上":2})
data

YearsExperience  EducationLevel City  Salary
0               3.0               1  城市A    45.9
1               7.8               2  城市C    80.5
2               2.3               0  城市A    25.2
3               5.1               0  城市A    30.4
4              10.0               2  城市B    65.7
5               1.2               2  城市C    60.8
6               8.6               1  城市C    50.1
7               6.9               2  城市A    70.3
8               4.2               1  城市A    40.7
9               2.4               0  城市A    28.1
10              5.3               0  城市A    32.0
11              3.9               1  城市A    48.3
12              7.2               2  城市C    84.2
13             10.0               2  城市B    70.9
14              1.5               2  城市C    62.4
15              8.4               1  城市C    55.6
16              6.5               2  城市A    72.7
17              4.8               1  城市A    42.9
18              2.1               0  城市A    26.5
19              5.2               0  城市A    31.6
20              3.5               1  城市A    43.8
21              7.6               2  城市C    78.3
22             10.0               2  城市B    63.6
23              1.8               2  城市C    58.0
24              8.2               1  城市C    48.3
25              6.3               2  城市A    68.4
26              4.6               1  城市A    38.5
27              2.5               0  城市A    24.9
28              5.0               0  城市A    29.7
29              3.6               1  城市A    41.6
30              7.4               2  城市C    76.9
31             10.0               2  城市B    60.2
32              1.7               2  城市C    56.3
33              8.0               1  城市C    45.2
34              6.1               2  城市A    65.9
35              4.3               1  城市A    36.7

In [191]:
#文字數字化
from sklearn.preprocessing import OneHotEncoder
onehot_encoder = OneHotEncoder()
onehot_encoder.fit(data[["City"]])
city_encoded = onehot_encoder.transform(data[["City"]]).toarray()
city_encoded

array([[ 1.00e+00,  0.00e+00,  0.00e+00],
       [ 0.00e+00,  0.00e+00,  1.00e+00],
       [ 1.00e+00,  0.00e+00,  0.00e+00],
       [ 1.00e+00,  0.00e+00,  0.00e+00],
       [ 0.00e+00,  1.00e+00,  0.00e+00],
       [ 0.00e+00,  0.00e+00,  1.00e+00],
       [ 0.00e+00,  0.00e+00,  1.00e+00],
       [ 1.00e+00,  0.00e+00,  0.00e+00],
       [ 1.00e+00,  0.00e+00,  0.00e+00],
       [ 1.00e+00,  0.00e+00,  0.00e+00],
       [ 1.00e+00,  0.00e+00,  0.00e+00],
       [ 1.00e+00,  0.00e+00,  0.00e+00],
       [ 0.00e+00,  0.00e+00,  1.00e+00],
       [ 0.00e+00,  1.00e+00,  0.00e+00],
       [ 0.00e+00,  0.00e+00,  1.00e+00],
       [ 0.00e+00,  0.00e+00,  1.00e+00],
       [ 1.00e+00,  0.00e+00,  0.00e+00],
       [ 1.00e+00,  0.00e+00,  0.00e+00],
       [ 1.00e+00,  0.00e+00,  0.00e+00],
       [ 1.00e+00,  0.00e+00,  0.00e+00],
       [ 1.00e+00,  0.00e+00,  0.00e+00],
       [ 0.00e+00,  0.00e+00,  1.00e+00],
       [ 0.00e+00,  1.00e+00,  0.00e+00],
       [ 0.00e+00,  0.00e+00,  1.0

In [192]:
#增加"CityA","CityB","CityC"欄位
data[["CityA","CityB","CityC"]] = city_encoded
data[["CityA","CityB","CityC"]]


CityA  CityB  CityC
0     1.0    0.0    0.0
1     0.0    0.0    1.0
2     1.0    0.0    0.0
3     1.0    0.0    0.0
4     0.0    1.0    0.0
5     0.0    0.0    1.0
6     0.0    0.0    1.0
7     1.0    0.0    0.0
8     1.0    0.0    0.0
9     1.0    0.0    0.0
10    1.0    0.0    0.0
11    1.0    0.0    0.0
12    0.0    0.0    1.0
13    0.0    1.0    0.0
14    0.0    0.0    1.0
15    0.0    0.0    1.0
16    1.0    0.0    0.0
17    1.0    0.0    0.0
18    1.0    0.0    0.0
19    1.0    0.0    0.0
20    1.0    0.0    0.0
21    0.0    0.0    1.0
22    0.0    1.0    0.0
23    0.0    0.0    1.0
24    0.0    0.0    1.0
25    1.0    0.0    0.0
26    1.0    0.0    0.0
27    1.0    0.0    0.0
28    1.0    0.0    0.0
29    1.0    0.0    0.0
30    0.0    0.0    1.0
31    0.0    1.0    0.0
32    0.0    0.0    1.0
33    0.0    0.0    1.0
34    1.0    0.0    0.0
35    1.0    0.0    0.0

In [193]:
#減少City,CityC
data = data.drop(["City","CityC"],axis = 1 )
data

YearsExperience  EducationLevel  Salary  CityA  CityB
0               3.0               1    45.9    1.0    0.0
1               7.8               2    80.5    0.0    0.0
2               2.3               0    25.2    1.0    0.0
3               5.1               0    30.4    1.0    0.0
4              10.0               2    65.7    0.0    1.0
5               1.2               2    60.8    0.0    0.0
6               8.6               1    50.1    0.0    0.0
7               6.9               2    70.3    1.0    0.0
8               4.2               1    40.7    1.0    0.0
9               2.4               0    28.1    1.0    0.0
10              5.3               0    32.0    1.0    0.0
11              3.9               1    48.3    1.0    0.0
12              7.2               2    84.2    0.0    0.0
13             10.0               2    70.9    0.0    1.0
14              1.5               2    62.4    0.0    0.0
15              8.4               1    55.6    0.0    0.0
16              6.5               2    72.7    1.0    0.0
17              4.8               1    42.9    1.0    0.0
18              2.1               0    26.5    1.0    0.0
19              5.2               0    31.6    1.0    0.0
20              3.5               1    43.8    1.0    0.0
21              7.6               2    78.3    0.0    0.0
22             10.0               2    63.6    0.0    1.0
23              1.8               2    58.0    0.0    0.0
24              8.2               1    48.3    0.0    0.0
25              6.3               2    68.4    1.0    0.0
26              4.6               1    38.5    1.0    0.0
27              2.5               0    24.9    1.0    0.0
28              5.0               0    29.7    1.0    0.0
29              3.6               1    41.6    1.0    0.0
30              7.4               2    76.9    0.0    0.0
31             10.0               2    60.2    0.0    1.0
32              1.7               2    56.3    0.0    0.0
33              8.0               1    45.2    0.0    0.0
34              6.1               2    65.9    1.0    0.0
35              4.3               1    36.7    1.0    0.0

In [194]:
from sklearn.model_selection import train_test_split
#y = a1*x1+a2*x2+...+b
x = ["YearsExperience","EducationLevel","CityA","CityB"]
y = ["Salary"]
#分成訓練集合測試集
x_train,x_test,y_train,y_test = train_test_split(data[x],data[y],test_size= 0.2,random_state=1)
#轉成numpy格式比較好處理
x_train = x_train.to_numpy()
x_test = x_test.to_numpy()
y_train = y_train.to_numpy()
y_test = y_test.to_numpy()



In [195]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)
x_train

array([[-6.57e-01, -3.39e-01,  9.31e-01, -4.08e-01],
       [-3.11e-01, -3.39e-01,  9.31e-01, -4.08e-01],
       [-1.04e+00, -1.69e+00,  9.31e-01, -4.08e-01],
       [ 8.65e-01, -3.39e-01, -1.07e+00, -4.08e-01],
       [ 9.34e-01, -3.39e-01, -1.07e+00, -4.08e-01],
       [ 2.77e-01,  1.02e+00,  9.31e-01, -4.08e-01],
       [ 1.56e+00,  1.02e+00, -1.07e+00,  2.45e+00],
       [-1.11e+00, -1.69e+00,  9.31e-01, -4.08e-01],
       [-1.38e+00,  1.02e+00, -1.07e+00, -4.08e-01],
       [-6.92e-02, -1.69e+00,  9.31e-01, -4.08e-01],
       [-1.31e+00,  1.02e+00, -1.07e+00, -4.08e-01],
       [ 1.56e+00,  1.02e+00, -1.07e+00,  2.45e+00],
       [ 1.56e+00,  1.02e+00, -1.07e+00,  2.45e+00],
       [-6.92e-01, -3.39e-01,  9.31e-01, -4.08e-01],
       [-1.18e+00, -1.69e+00,  9.31e-01, -4.08e-01],
       [ 1.07e+00, -3.39e-01, -1.07e+00, -4.08e-01],
       [ 1.56e+00,  1.02e+00, -1.07e+00,  2.45e+00],
       [ 4.84e-01,  1.02e+00,  9.31e-01, -4.08e-01],
       [-4.15e-01, -3.39e-01,  9.31e-01, -4.08

In [196]:
a = [1,2,3,4]
b = 1
y_pred = (x_train*a).sum(axis = 1)+b
print(y_train.shape)

print(y_pred.shape)


(28, 1)
(28,)


In [197]:
# find best a,b
# y = a1x1+a2x2+...+b
((y_train - y_pred)**2).mean()

np.float64(2869.6762694377244)

In [198]:
#製成函數
import numpy as np
def compute_cost(x,y,a,b):
   y_pred = (x*a).sum(axis = 1)+b
   cost = ((y - y_pred)**2).mean()
   return cost

In [199]:
a = np.array([1,2,3,4])
b = 1
compute_cost(x_train,y_train,a,b)

np.float64(2869.6762694377244)

In [200]:
y_pred = (x_train*a).sum(axis = 1)+b
y_pred = y_pred.reshape(28,1)
b_gradient = (y_pred - y_train).mean()

# b_gradient
#w1 = x_train[:,0]
#w1_gradient = ((y_pred - y_train)*x_train[:,0]).mean()
#w2_gradient = ((y_pred - y_train)*x_train[:,1]).mean()
#w3_gradient = ((y_pred - y_train)*x_train[:,2]).mean()
#w4_gradient = ((y_pred - y_train)*x_train[:,3]).mean()
#測試w1_gradient
w_gradient = np.zeros(x_train.shape[1])
for i in range(x_train.shape[1]):
   w_gradient[i] = ((y_pred - y_train)*x_train[:,i]).mean()
w_gradient




array([-1.52e-14,  1.81e-17,  1.60e-15, -3.66e-15])

In [201]:
def compute_gradient(x,y,a,b):
  y_pred = (x_train*a).sum(axis = 1)+b
  b_gradient = (y_pred - y_train).mean()
  for i in range(x_train.shape[1]):
    w_gradient[i] = ((y_pred - y_train)*x_train[:,i]).mean()
  return w_gradient,b_gradient



In [202]:
a = np.array([1,2,3,4])
b = 1
compute_gradient(x,y,a,b)

(array([ 2.84e+00,  2.42e+00, -3.93e-01,  4.15e+00]),
 np.float64(-50.692857142857136))

In [203]:
def compute_cost(x,y,a,b):
   y_pred = (x*a).sum(axis = 1)+b
   cost = ((y - y_pred)**2).mean()
   return cost


In [204]:

def GradDesc(x,y,ainit,binit,learningRate,computeCost,compute_gradient,itera,iteraShow):
  a = ainit
  b = binit
  ahist = []
  bhist = []
  chist = []
  for i in range(itera):
    aGrad,bGrad = compute_gradient(x,y,a,b)
    a = a - aGrad*learningRate
    b = b - bGrad*learningRate
    ahist.append(a)
    bhist.append(b)
    chist.append(computeCost(x,y,a,b))
    if i%iteraShow == 0:
      print(f"{i: 6}nd , cost:{computeCost(x,y,a,b)} , a:{a} , b:{b}, aG:{aGrad} , bG:{bGrad}")
  return a,b,ahist,bhist,chist

In [205]:
#ainit = np.array([1,2,3,4])
#binit = 1
#learningRate =1.0e-2

#itera = 2000
#iteraShow = 1000
#GradDesc(x,y,ainit,binit,learningRate,compute_cost,compute_gradient,itera,iteraShow)

In [206]:
import pandas as pd
import numpy as np
np.set_printoptions(formatter = {'float':'{: .2e}'.format})
url = "https://raw.githubusercontent.com/GrandmaCan/ML/main/Resgression/Salary_Data2.csv"
data = pd.read_csv(url)
data["EducationLevel"] = data["EducationLevel"].map({"高中以下":0,"大學":1,"碩士以上":2})
from sklearn.preprocessing import OneHotEncoder
onehot_encoder = OneHotEncoder()
onehot_encoder.fit(data[["City"]])
city_encoded = onehot_encoder.transform(data[["City"]]).toarray()
data[["CityA","CityB","CityC"]] = city_encoded
data = data.drop(["City","CityC"],axis = 1 )
from sklearn.model_selection import train_test_split
#y = a1*x1+a2*x2+...+b
x = data[["YearsExperience","EducationLevel","CityA","CityB"]]
y = data["Salary"]
#分成訓練集合測試集
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

#轉成numpy格式比較好處理

x_train = x_train.to_numpy()
x_test = x_test.to_numpy()

def compute_gradient(x,y,a,b):
  y_pred = (x*a).sum(axis = 1) + b
  b_gradient = (y_pred - y).mean()
  a_gradient = np.zeros(x.shape[1])
  for i in range(x.shape[1]):
    a_gradient[i] = (x[:,i]*(y_pred - y)).mean()
  return a_gradient,b_gradient

def compute_cost(x,y,a,b):
   y_pred = (x*a).sum(axis = 1) + b
   cost = ((y - y_pred)**2).mean()
   return cost
"""
x = x_train
y = y_train
a = np.array([1,2,3,4])
b= 1
learningRate = 0.01
agra,bgra = compute_gradient(x,y,a,b)
print(compute_cost(x,y,a,b))
a = a - agra*learningRate
b = b - bgra*learningRate
print(compute_cost(x,y,a,b))

"""
def GradDesc(x,y,ainit,binit,learningRate,compute_cost,compute_gradient,itera,iteraShow):
  a = ainit
  b = binit
  ahist = []
  bhist = []
  chist = []
  for i in range(itera):
    a_gradient,b_gradient = compute_gradient(x,y,a,b)
    a = a - a_gradient*learningRate
    b = b - b_gradient*learningRate
    ahist.append(a)
    bhist.append(b)
    chist.append(compute_cost(x,y,a,b))
    if i%iteraShow == 0:
      print(f"{i: 6}nd , cost:{compute_cost(x,y,a,b): .2e} , a:{a} , b:{b:.2e}, aG:{a_gradient} , bG:{b_gradient:.2e}")
  return a,b,ahist,bhist,chist


ainit = np.array([1,2,2,4])
binit = 0
learningRate =1.0e-2

itera = 20001
iteraShow = 2000
a, b, ahist, bhist, chist = GradDesc(x_train, y_train, ainit, binit, learningRate, compute_cost, compute_gradient, itera, iteraShow)#記得要用變數接住return值


     0nd , cost: 9.11e+02 , a:[ 3.46e+00  2.62e+00  2.19e+00  4.07e+00] , b:4.21e-01, aG:[-2.46e+02 -6.19e+01 -1.88e+01 -6.73e+00] , bG:-4.21e+01
  2000nd , cost: 2.71e+01 , a:[ 1.78e+00  2.07e+01  2.03e+00 -8.50e+00] , b:1.59e+01, aG:[-1.39e-03  4.68e-02  1.67e-01  2.28e-01] , bG:-1.82e-01
  4000nd , cost: 2.54e+01 , a:[ 1.77e+00  2.01e+01  9.10e-02 -1.08e+01] , b:1.82e+01, aG:[ 1.40e-03  1.70e-02  5.06e-02  4.44e-02] , bG:-6.56e-02
  6000nd , cost: 2.53e+01 , a:[ 1.74e+00  1.99e+01 -5.17e-01 -1.12e+01] , b:1.91e+01, aG:[ 1.06e-03  6.46e-03  1.67e-02  6.56e-03] , bG:-2.50e-02
  8000nd , cost: 2.53e+01 , a:[ 1.73e+00  1.98e+01 -7.24e-01 -1.12e+01] , b:1.94e+01, aG:[ 5.58e-04  2.56e-03  5.94e-03 -1.04e-04] , bG:-9.88e-03
 10000nd , cost: 2.53e+01 , a:[ 1.72e+00  1.98e+01 -7.99e-01 -1.12e+01] , b:1.95e+01, aG:[ 2.61e-04  1.04e-03  2.24e-03 -7.20e-04] , bG:-4.01e-03
 12000nd , cost: 2.53e+01 , a:[ 1.72e+00  1.98e+01 -8.28e-01 -1.12e+01] , b:1.96e+01, aG:[ 1.16e-04  4.27e-04  8.81e-04 -4.6

In [207]:
y_pred = (a*x_test).sum(axis=1) + b
pd.DataFrame({
    "y_pred": y_pred,
    "y_test": y_test
})

y_pred  y_test
30  71.832034    76.9
34  68.758181    65.9
28  27.319488    29.7
3   27.490780    30.4
19  27.662072    31.6
17  46.754144    42.9
21  72.174619    78.3
23  62.239675    58.0